name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Mis à jour de v3 à v4

    - name: Install Python
      uses: actions/setup-python@v5 # Mis à jour de v4 à v5
      with:
        python-version: '3.10'

    - name: Install Graphviz System
      run: choco install graphviz -y

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        # On installe graphviz ici pour que PyInstaller puisse lire ton code
        pip install PyQt6 graphviz pyinstaller 

    - name: Build EXE with PyInstaller
      run: |
        # On définit où se trouve Graphviz sur la machine GitHub
        $G_BIN = "C:/Program Files/Graphviz/bin"
        
        # On crée l'exe en incluant les fichiers .exe et .dll de Graphviz
        pyinstaller --onefile --windowed `
          --add-binary "${G_BIN}/*.exe;graphviz_bin" `
          --add-binary "${G_BIN}/*.dll;graphviz_bin" `
          interface.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # C'est ICI que l'erreur se trouvait (v3 -> v4)
      with:
        name: MonApplicationWindows
        path: dist/interface.exe
